version: '{build}'

branches:
  only:
  - master
  - WX_3_0_BRANCH

skip_commits:
  files:
    - docs/
    - interface/
    - misc/
    - include/wx/osx/
    - src/osx/
    - .github/workflows/
    - .travis.yml
    - build/tools/travis-ci.sh
    - build/tools/before_install.sh

environment:
  matrix:
  - TOOLSET: msbuild
    CONFIGURATION: DLL Release
    ARCH: x64
    wxUSE_STL: 1
  - TOOLSET: nmake
    VS: '9.0'
    BUILD: release
    ARCH: x86
  - TOOLSET: nmake
    VS: '14.0'
    BUILD: debug
    ARCH: amd64
    wxUSE_STL: 1
    wxUSE_WEBVIEW_EDGE: 1
  - TOOLSET: mingw
  - TOOLSET: msys2
    MSYSTEM: MINGW32
  - TOOLSET: cygwin
  - TOOLSET: cmake
    GENERATOR: 'Visual Studio 12'
    SHARED: ON
    CONFIGURATION: Release
  - TOOLSET: cmake_qt
    GENERATOR: 'Visual Studio 14 2015 Win64'
    SHARED: ON
    CONFIGURATION: Release

clone_depth: 50

install: git submodule update --init

init:
- ps: |
    if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
        https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
        Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
        throw "There are newer queued builds for this pull request, failing early." }

before_build:
- ps: |
    $env:PATH = $env:PATH -replace "C:\\Program Files\\Git\\usr\\bin",""
    if (-not (Test-Path env:wxUSE_STL)) { $env:wxUSE_STL = '0' }
    if (-not (Test-Path env:wxUSE_WEBVIEW_EDGE)) { $env:wxUSE_WEBVIEW_EDGE = '0' }
    if (($env:compiler -ne "msys2") -and ($env:compiler -ne "cygwin")) {
      gc include\wx\msw\setup0.h |
      %{$_ -replace "define wxUSE_STL 0", "define wxUSE_STL $env:wxUSE_STL"} |
      %{$_ -replace "define wxUSE_WEBVIEW_EDGE 0", "define wxUSE_WEBVIEW_EDGE $env:wxUSE_WEBVIEW_EDGE"} |
      sc include\wx\msw\setup.h
    }

build_script: c:\projects\wxwidgets\build\tools\appveyor.bat

before_test:
- ps: |
    Write-Output "Getting and launching httpbin."
    C:\Python35\Scripts\pip.exe --disable-pip-version-check --no-warn-script-location install httpbin
    Start-Job -Name wx_httpbin { C:\Python35\python.exe -m httpbin.core 2>&1 > c:\projects\wxwidgets\httpbin.log }
    curl http://127.0.0.1:5000/ip
    $env:WX_TEST_WEBREQUEST_URL="http://127.0.0.1:5000"

test_script: c:\projects\wxwidgets\build\tools\appveyor-test.bat

after_test:
- ps: |
    Stop-Job -Name wx_httpbin
