# This workflow does some quick checks.
name: Code Checks

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/code_checks.yml'
      - 'docs/**'
      - 'include/**'
      - 'interface/**'
      - 'misc/suppressions/**'
      - '**/*.md'
      - '!docs/changes*txt'
  pull_request:
    branches:
      - master
    paths:
      - '.github/workflows/code_checks.yml'
      - 'docs/**'
      - 'include/**'
      - 'interface/**'
      - 'misc/suppressions/**'
      - '**/*.md'
      - '!docs/changes*txt'

jobs:
  check-unix:
    runs-on: ubuntu-20.04
    name: Check Spelling

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install codespell
        run: |
          pip install codespell==1.17.1

      - name: Run codespell
        run: |
          codespell -I misc/suppressions/codespell-words -x misc/suppressions/codespell-lines -S 'docs/changes.txt,docs/changes_30.txt,*.png,*.ico,*.bmp,*.cur,docs/doxygen/images' README.md docs include interface
